GET http://localhost:3333/questions

###

POST http://localhost:3333/questions
Content-Type: application/json

{
    "label": "Quanto tempo dura uma partida de futebol?",
    "possibleAnswers": ["75 Minutos","90 Minutos","100 Minutos", "60 Minutos"],
    "correctAnswer": "90 Minutos",
    "levelDifficulty": "Fácil (4pts)",
    "points": 4
}

###

PUT http://localhost:3333/questions/ff1e1e6c-d09d-43fa-8d3f-4caf929af388
Content-Type: application/json

{
    "label": "Quanto tempo dura na cama?",
    "possibleAnswers": ["75 Minutos","90 Minutos","100 Minutos", "60 Minutos"],
    "correctAnswer": "90 Minutos",
    "levelDifficulty": "Fácil (4pts)",
    "points": 4
}

###

DELETE http://localhost:3333/questions/ff1e1e6c-d09d-43fa-8d3f-4caf929af388
